
services:
  backend:
    image: us-central1-docker.pkg.dev/single-patrol-444420-s3/project-management-app-docker/project_management_app-backend/latest
    container_name: django-backend
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - "media:/app/media"
    command: bash -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 project_management_app.asgi:application"
    environment:
      POSTGRESQL_PASS: ${POSTGRESQL_PASS}
      GOOGLE_OAUTH2_CLIENT_ID: ${GOOGLE_OAUTH2_CLIENT_ID}
      GOOGLE_OAUTH2_CLIENT_SECRET: ${GOOGLE_OAUTH2_CLIENT_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}

  nginx:
    image: us-central1-docker.pkg.dev/single-patrol-444420-s3/project-management-app-docker/project_management_app-nginx/latest
    container_name: nginx-web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - "media:/app/media"
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./default.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:80 || exit 1"]
      interval: 1m30s
      timeout: 20s
      retries: 5
      start_period: 30s

  db:
    image: us-central1-docker.pkg.dev/single-patrol-444420-s3/project-management-app-docker/postgres/latest
    container_name: postgres-db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_DB: project_management_db
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      POSTGRES_USER: postgres

  # certbot:
  #  image: certbot/certbot
  #  container_name: certbot
  #  depends_on:
  #    - nginx
  #  volumes:
  #    - ./certbot/conf:/etc/letsencrypt
  #    - ./certbot/www:/var/www/certbot
  #  command: certonly --webroot -w /var/www/certbot --force-renewal --email placeholder@gmail.com -d task-track.ddns.net --agree-tos


volumes:
  db-data:
  media: