# Generated by Django 4.2.15 on 2024-10-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(default='document', editable=False, max_length=50),
        ),
    ]
