# Generated by Django 4.2.15 on 2024-10-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_document_content_alter_document_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
