# Generated by Django 4.2.15 on 2024-11-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['order']},
        ),
    ]
