# Generated by Django 4.2.15 on 2024-10-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_default_profile_picture',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile-pictures/'),
        ),
    ]
