# Generated by Django 4.2.15 on 2024-11-18 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Workspace', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces_created', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='workspaces_joined', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
