# Generated by Django 4.2.15 on 2024-11-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_create_workspaces_for_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_main',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
