# Generated by Django 4.2.15 on 2024-11-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_workspace_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='color',
            field=models.CharField(default='bg-sky-400', max_length=255),
        ),
    ]
