# Generated by Django 4.2.15 on 2024-11-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_workspace_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='cover_color',
            field=models.CharField(default='bg-slate-100', max_length=255),
        ),
        migrations.AddField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
