# Generated by Django 4.2.15 on 2024-11-19 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        ('workspace_elements', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceelement',
            name='workspace',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace', null=True),
            preserve_default=False,
        ),
    ]
