# Generated by Django 4.2.15 on 2024-11-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_create_workspaces_for_existing_users'),
        ('workspace_elements', '0003_workspaceelement_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceelement',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
    ]
