# Generated by Django 4.2.15 on 2024-10-25 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Board', max_length=255)),
                ('description', models.CharField(default="Add your board's description here", max_length=2550)),
                ('type', models.CharField(default='board', editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('column_type', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Group', max_length=255)),
                ('order', models.IntegerField()),
                ('color', models.CharField(default='bg-sky-400', max_length=255)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New item', max_length=2550)),
                ('order', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.group')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('value_color', models.CharField(blank=True, default='bg-neutral-400', max_length=255, null=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.column')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.item')),
                ('value_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['column__order'],
            },
        ),
        migrations.CreateModel(
            name='BoardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
            ],
        ),
    ]
