# Generated by Django 4.2.15 on 2024-08-25 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_board_title_board_created_at_board_name_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New item', max_length=2550)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.group')),
            ],
        ),
    ]
