# Generated by Django 4.2.15 on 2024-08-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
