# Generated by Django 4.2.15 on 2024-09-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
