# Generated by Django 4.2.15 on 2024-09-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_group_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(default='bg-sky-400', max_length=255),
        ),
    ]
