# Generated by Django 4.2.15 on 2024-09-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_column_columnvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnvalue',
            name='value_color',
            field=models.CharField(blank=True, default='bg-neutral-400', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='columnvalue',
            name='value_text',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
