# Generated by Django 4.2.15 on 2024-09-06 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_columnvalue_value_color_alter_columnvalue_value_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='board',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='boards.board'),
            preserve_default=False,
        ),
    ]
