# Generated by Django 4.2.15 on 2024-09-07 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_column_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columnvalue',
            options={'ordering': ['column__order']},
        ),
    ]
