# Generated by Django 4.2.15 on 2024-09-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_alter_columnvalue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(default="Add your board's description here", max_length=2550),
        ),
    ]
