# Generated by Django 4.2.15 on 2024-10-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_boardview'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
