# Generated by Django 4.2.15 on 2024-12-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notifications_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('invite', 'Invite'), ('member left workspace', 'Member left workspace')], max_length=50),
        ),
    ]
